api:
  url: https://back.halykbank.kz/common/currency-history

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
# ?????? ???? ?????? ? ??????, ????????