api:
  v1:
    url: https://back.halykbank.kz/common/currency-history
  v2:
    url: https://api.currencyapi.com/v3/latest
    key: PKLJzvgv4OXzRmDSRqMThopJ7gJHpupHQ9gSoIbt
    base_currency: KZT
    currencies: EUR

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
