api:
  v1:
    url: https://back.halykbank.kz/common/currency-history #Бесплатная версия с нашим отечественным банком, но за последние 3 дня
  v2:
    url: https://api.currencyfreaks.com/v2.0/timeseries
    apikey: f58d54abc6ff45d0b76be28c060852f6
    start-date: 2024-08-17 #За последние 10 дней, к сожалению фича платная
    end-date: 2022-08-07
    base_currency: EUR
    currencies: KZT

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
